
#!------[Makefile]------
#Hedef: bağımlılıklar
#*	 g++ $< -o bin/$@
#*	 ./bin/$@

bitwase: bitwase_main.cpp
	g++ $< -o bin/$@
	./bin/$@
Class: Class_main.cpp
	g++ $< -o bin/$@
	./bin/$@
vectors: vectors_main.cpp
	g++ $< -o bin/$@
	./bin/$@
AsalBul: AsalBul_main.cpp
	g++ $< -o bin/$@
	./bin/$@