# ! MAKEFİLE

main: main.cpp
	g++ $< -o bin/$@
	./bin/$@
main2: main2.cpp
	g++ $< -o bin/$@
	./bin/$@
main3: main3.cpp
	g++ $< -o bin/$@
	./bin/$@
main4: main4.cpp
	g++ $< -o bin/$@
	./bin/$@
main5: main5.cpp
	g++ $< -o bin/$@
	./bin/$@
main6: main6.cpp	
	g++ $< -o bin/$@
	./bin/$@
main7: main7.cpp
	g++ $< -o bin/$@
	./bin/$@
